/*
 * Audio Player HTML5 v3.4
 * Copyright 2012-2021, LambertGroup
 *
 */

 (function(e){function P(a){a=document.getElementById(a.audioID);return!(!a.canPlayType||!a.canPlayType("audio/mpeg;").replace(/no/,""))}function R(a){var c=navigator.userAgent;if(c.match(/iPad/i)||c.match(/iPhone/i)){a.userOS="iOS";var f=c.indexOf("OS ")}else c.match(/Android/i)?(a.userOS="Android",f=c.indexOf("Android ")):a.userOS="unknown";a.userOSver="iOS"===a.userOS&&-1<f?c.substr(f+3,3).replace("_","."):"Android"===a.userOS&&-1<f?c.substr(f+8,3):"unknown"}function H(a,c,f,d,h,k,g,l,p,m,x,u,r,
 D){a.totalTime="Infinity";c.isSliderInitialized&&(p.slider("destroy"),c.isSliderInitialized=!1);c.isProgressInitialized&&(m.progressbar("destroy"),c.isProgressInitialized=!1);a.is_changeSrc=!0;a.is_buffer_complete=!1;u.width(a.audioPlayerWidth);m.css({background:c.bufferEmptyColor});a.curSongText="";c.showAuthor&&null!=a.playlist_arr[a.current_img_no].author&&""!=a.playlist_arr[a.current_img_no].author&&(a.curSongText+=a.playlist_arr[a.current_img_no].author+" - ");c.showTitle&&null!=a.playlist_arr[a.current_img_no].title&&
 ""!=a.playlist_arr[a.current_img_no].title&&(a.curSongText+=a.playlist_arr[a.current_img_no].title);a.isAuthorTitleInsideScrolling=!1;a.authorTitleInsideWait=0;r.stop();r.css({"margin-left":0});r.html(a.curSongText);a.curSongText||u.css({display:"none",width:0,height:0,padding:0,margin:0});g=document.getElementById(a.audioID);e(f[a.current_img_no]).css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor});I(-1,a,c,d,h,k);
 c=a.playlist_arr[a.current_img_no].sources_mp3;if(-1!=t.indexOf("opera")||-1!=t.indexOf("opr")||-1!=t.indexOf("firefox")||-1!=t.indexOf("mozzila"))c=a.playlist_arr[a.current_img_no].sources_ogg,""!=P(a)&&(c=a.playlist_arr[a.current_img_no].sources_mp3);if(-1!=t.indexOf("chrome")||-1!=t.indexOf("msie")||-1!=t.indexOf("safari"))c=a.playlist_arr[a.current_img_no].sources_mp3,-1!=t.indexOf("opr")&&(c=a.playlist_arr[a.current_img_no].sources_ogg,""!=P(a)&&(c=a.playlist_arr[a.current_img_no].sources_mp3));
 -1!=t.indexOf("android")&&(c=a.playlist_arr[a.current_img_no].sources_mp3);"iOS"===a.userOS&&(c=a.playlist_arr[a.current_img_no].sources_mp3);g.src=c;document.getElementById(a.audioID).load()}function E(a){var c=10>Math.floor(a/60)?"0"+Math.floor(a/60):Math.floor(a/60);return c+":"+(10>Math.floor(a-60*c)?"0"+Math.floor(a-60*c):Math.floor(a-60*c))}function L(a,c,f,d,h,k,g,l){a.is_changeSrc=!1;a.is_very_first&&(a.is_very_first=!1);h.width(a.audioPlayerWidth);d.width(a.audioPlayerWidth);d.slider({value:0,
 step:.01,orientation:"horizontal",range:"min",max:a.totalTime,slide:function(){a.is_seeking=!0},stop:function(p,m){a.is_seeking=!1;document.getElementById(a.audioID).currentTime=m.value;0!=document.getElementById(a.audioID).paused&&(document.getElementById(a.audioID).play(),g.addClass("AudioPause"))},create:function(p,m){c.isSliderInitialized=!0}});e(".ui-slider-range",d).css({background:c.seekbarColor});h.progressbar({value:0,complete:function(){a.is_buffer_complete=!0},create:function(p,m){c.isProgressInitialized=
 !0}});e(".ui-widget-header",h).css({background:c.bufferFullColor})}function S(a,c,f,d,h,k,g,l,p,m){!a.isAuthorTitleInsideScrolling&&5<=a.authorTitleInsideWait&&m.width()>a.audioPlayerWidth?(a.isAuthorTitleInsideScrolling=!0,a.authorTitleInsideWait=0,m.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),m.css({"margin-left":0}),m.stop().animate({"margin-left":a.audioPlayerWidth-m.width()+"px"},parseInt(1E4*(m.width()-a.audioPlayerWidth)/
 150,10),"linear",function(){a.isAuthorTitleInsideScrolling=!1})):!a.isAuthorTitleInsideScrolling&&m.width()>a.audioPlayerWidth&&a.authorTitleInsideWait++;curTime=document.getElementById(a.audioID).currentTime;bufferedTime=0;a.is_changeSrc&&!isNaN(a.totalTime)&&"Infinity"!=a.totalTime&&L(a,c,f,d,h,k,g,l);!a.is_seeking&&c.isSliderInitialized&&d.slider("value",curTime);-1!=t.indexOf("android")?(a.totalTime!=document.getElementById(a.audioID).duration&&0<document.getElementById(a.audioID).duration&&(a.totalTime=
 document.getElementById(a.audioID).duration,c.isSliderInitialized&&(d.slider("destroy"),c.isSliderInitialized=!1),c.isProgressInitialized&&(h.progressbar("destroy"),c.isProgressInitialized=!1),L(a,c,f,d,h,k,g,l)),h.css({background:c.bufferFullColor}),isNaN(a.totalTime)||"Infinity"==a.totalTime?k.text("00:00 / "+E(0)):k.text(E(curTime)+" / "+E(a.totalTime))):(document.getElementById(a.audioID).buffered.length&&(bufferedTime=document.getElementById(a.audioID).buffered.end(document.getElementById(a.audioID).buffered.length-
 1),0<bufferedTime&&!a.is_buffer_complete&&!isNaN(a.totalTime)&&"Infinity"!=a.totalTime&&c.isProgressInitialized&&h.progressbar({value:100*bufferedTime/a.totalTime})),isNaN(a.totalTime)||"Infinity"==a.totalTime?k.text(E(curTime)+" / "+E(bufferedTime)):k.text(E(curTime)+" / "+E(a.totalTime)));z(c,"cookie_timePlayed",curTime)}function I(a,c,f,d,h,k){if(c.total_images>f.numberOfThumbsPerScreen){var g=(d.height()+1)*(c.total_images-f.numberOfThumbsPerScreen),l=0;k.stop(!0,!0);e("html, body").off("touchstart touchmove").on("touchstart touchmove",
 function(p){p.preventDefault()});-1==a||c.isCarouselScrolling?!c.isCarouselScrolling&&c.total_images>f.numberOfThumbsPerScreen&&(c.isCarouselScrolling=!0,l=-1*parseInt((d.height()+1)*c.current_img_no,10),Math.abs(l)>g&&(l=-1*g),c.total_images>f.numberOfThumbsPerScreen&&f.showPlaylist&&h.slider("value",100+parseInt(100*l/g)),k.animate({top:l+"px"},500,"easeOutCubic",function(){c.isCarouselScrolling=!1;e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(p){})})):(c.isCarouselScrolling=
 !0,1>=a&&(a=0),l=2>=a?-1*g:parseInt(g*(a-100)/100,10),0<l&&(l=0),k.animate({top:l+"px"},1100,"easeOutQuad",function(){c.isCarouselScrolling=!1;e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(p){})}))}}function z(a,c,f,d){a.continuouslyPlayOnAllPages&&(a=new Date,a.setDate(a.getDate()+d),f=escape(f)+(null==d?"":"; expires="+a.toUTCString())+";path=/",document.cookie=c+"="+f)}function F(a,c){if(a.continuouslyPlayOnAllPages){var f,d=document.cookie.split(";");for(f=0;f<
 d.length;f++){var h=d[f].substr(0,d[f].indexOf("="));var k=d[f].substr(d[f].indexOf("=")+1);h=h.replace(/^\s+|\s+$/g,"");if(h==c)return unescape(k)}}}function M(a,c){var f=Math.ceil(Math.random()*(c.total_images-1));c.current_img_no=f!=c.current_img_no?f:Math.ceil(Math.random()*(c.total_images-1))}function T(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}function N(){e("audio").each(function(){e(".AudioPlay").removeClass("AudioPause");
 e(this)[0].pause()})}var t=navigator.userAgent.toLowerCase();e.audio1_html5={version:"1.0"};e.fn.audio1_html5=function(a){a=e.extend({},e.fn.audio1_html5.defaults,a);return this.each(function(){var c=e(this),f=e('<div class="AudioControls"> <a class="AudioRewind" title="Rewind"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioPrev" title="Previous"></a><a class="AudioNext" title="Next"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div> <div class="AudioTimer">00:00 / 00:00</div>  </div>   <div class="AudioBuffer"></div><div class="AudioSeek"></div><div class="songAuthorTitle"><div class="songAuthorTitleInside">AA</div></div>    <div class="thumbsHolderWrapper"><div class="playlistPadding"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>'),
 d=c.parent(".audio1_html5"),h=e(this).parent();d.addClass(a.skin);d.append(f);var k=e(".AudioControls",d);f=e(".AudioRewind",d);var g=e(".AudioPlay",d),l=e(".AudioPrev",d),p=e(".AudioNext",d),m=e(".AudioShowHidePlaylist",d),x=e(".VolumeButton",d),u=e(".VolumeSlider",d),r=e(".AudioTimer",d),D=e(".songAuthorTitle",d),G=e(".songAuthorTitleInside",d),A=e(".AudioBuffer",d),C=e(".AudioSeek",d);d.wrap("<div class='the_wrapper'></div>");var O=d.parent();T();d.css({background:a.playerBg,padding:a.playerPadding+
 "px"});var b={current_img_no:0,is_very_first:!0,total_images:0,is_seeking:!1,is_changeSrc:!1,is_buffer_complete:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",isCarouselScrolling:!1,isAuthorTitleInsideScrolling:!1,curSongText:"",authorTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,audioObj:"",cookie_timePlayed:0,cookie_current_img_no:0,cookie_initialVolume:0,cookie_muteVolume:0,cookie_autoPlay:!1,userOS:"",userOSver:0,html5_audio_tag:"",audioID:"audio4_audio_tag_id_"+Math.floor(1E5*
 Math.random())};b.html5_audio_tag=e('<audio id="'+b.audioID+'" preload="metadata"></audio>');d.append(b.html5_audio_tag);-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));R(b);"iOS"===b.userOS&&d.css({"padding-top":"0px"});b.audioPlayerWidth=
 0;a.showRewindBut?b.audioPlayerWidth+=f.width()+parseInt(f.css("margin-left").substring(0,f.css("margin-left").length-2))+parseInt(f.css("margin-right").substring(0,f.css("margin-right").length-2)):f.css({display:"none",width:0,height:0,padding:0,margin:0});a.showPlayBut?b.audioPlayerWidth+=g.width()+parseInt(g.css("margin-left").substring(0,g.css("margin-left").length-2))+parseInt(g.css("margin-right").substring(0,g.css("margin-right").length-2)):g.css({display:"none",width:0,height:0,padding:0,
 margin:0});a.showPreviousBut?b.audioPlayerWidth+=l.width()+parseInt(l.css("margin-left").substring(0,l.css("margin-left").length-2))+parseInt(l.css("margin-right").substring(0,l.css("margin-right").length-2)):l.css({display:"none",width:0,height:0,padding:0,margin:0});a.showNextBut?b.audioPlayerWidth+=p.width()+parseInt(p.css("margin-left").substring(0,p.css("margin-left").length-2))+parseInt(p.css("margin-right").substring(0,p.css("margin-right").length-2)):p.css({display:"none",width:0,height:0,
 padding:0,margin:0});a.showPlaylistBut?b.audioPlayerWidth+=m.width()+parseInt(m.css("margin-left").substring(0,m.css("margin-left").length-2))+parseInt(m.css("margin-right").substring(0,m.css("margin-right").length-2)):m.css({display:"none",width:0,height:0,padding:0,margin:0});a.showVolumeBut?b.audioPlayerWidth+=x.width()+parseInt(x.css("margin-left").substring(0,x.css("margin-left").length-2))+parseInt(x.css("margin-right").substring(0,x.css("margin-right").length-2)):x.css({display:"none",width:0,
 height:0,padding:0,margin:0});a.showVolumeSliderBut?b.audioPlayerWidth+=u.width()+parseInt(u.css("margin-left").substring(0,u.css("margin-left").length-2))+parseInt(u.css("margin-right").substring(0,u.css("margin-right").length-2)):u.css({display:"none",width:0,height:0,padding:0,margin:0});a.showTimer?b.audioPlayerWidth+=r.width()+parseInt(r.css("margin-left").substring(0,r.css("margin-left").length-2))+parseInt(r.css("margin-right").substring(0,r.css("margin-right").length-2)):r.css({display:"none",
 width:0,height:0,padding:0,margin:0});a.showSeekBar||(A.css({display:"none",width:0,height:0,padding:0,margin:0}),C.css({display:"none",width:0,height:0,padding:0,margin:0}));r.css({color:a.timerColor});D.css({color:a.songAuthorTitleColor});"iOS"===b.userOS?8>Number(b.userOSver)&&(b.audioPlayerWidth-=9):b.audioPlayerWidth-=9;-1!=t.indexOf("android")?a.playlistTopPos-=0:"iOS"===b.userOS&&(8>Number(b.userOSver)?k.css("margin-top","-9px"):k.css("margin-top","6px"),a.playlistTopPos-=5);h.width(b.audioPlayerWidth+
 10);a.showSeekBar||h.height(d.height()-4);a.showAuthor||a.showTitle||h.height(d.height()-22);b.audioPlayerHeight=d.height()+2*a.playerPadding;var v=e(".thumbsHolderWrapper",d);h=e(".playlistPadding",d);k=e(".thumbsHolderVisibleWrapper",d);var B=e(".thumbsHolder",d),q=e(".slider-vertical",d);a.showPlaylist||v.css({display:"none"});a.showPlaylistOnInit||v.css({opacity:0,"margin-top":"-20px",display:"none"});v.css({width:d.width()+2*a.playerPadding+"px",top:b.audioPlayerHeight+a.playlistTopPos+"px",
 left:"0px",background:a.playlistBgColor});k.width(d.width()+1+2*a.playerPadding);a.centerPlugin&&O.css({margin:"0 auto"});b.playlist_arr=[];e(".xaudioplaylist",d).children().each(function(){currentElement=e(this);b.total_images++;b.playlist_arr[b.total_images-1]=[];b.playlist_arr[b.total_images-1].title="";b.playlist_arr[b.total_images-1].author="";b.playlist_arr[b.total_images-1].thumb="";b.playlist_arr[b.total_images-1].sources_mp3="";b.playlist_arr[b.total_images-1].sources_ogg="";null!=currentElement.find(".xtitle").html()&&
 (b.playlist_arr[b.total_images-1].title=currentElement.find(".xtitle").html());null!=currentElement.find(".xauthor").html()&&(b.playlist_arr[b.total_images-1].author=currentElement.find(".xauthor").html());null!=currentElement.find(".xthumb").html()&&(b.playlist_arr[b.total_images-1].thumb=currentElement.find(".xthumb").html());null!=currentElement.find(".xsources_mp3").html()&&(b.playlist_arr[b.total_images-1].sources_mp3=currentElement.find(".xsources_mp3").html());null!=currentElement.find(".xsources_ogg").html()&&
 (b.playlist_arr[b.total_images-1].sources_ogg=currentElement.find(".xsources_ogg").html());thumbsHolder_Thumb=e('<div class="thumbsHolder_ThumbOFF" rel="'+(b.total_images-1)+'"><div class="padding">'+(a.showPlaylistNumber?b.total_images+". ":"")+b.playlist_arr[b.total_images-1].title+"</div></div>");B.append(thumbsHolder_Thumb);thumbsHolder_Thumb.css({top:(thumbsHolder_Thumb.height()+1)*b.total_images+"px",background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,
 color:a.playlistRecordTextOffColor});1!==b.total_images||a.shuffle||thumbsHolder_Thumb.css({background:a.playlistRecordBgOnColor,"border-bottom-color":a.playlistRecordBottomBorderOnColor,color:a.playlistRecordTextOnColor})});v.height(2*a.playlistPadding+(thumbsHolder_Thumb.height()+1)*(a.numberOfThumbsPerScreen<b.total_images?a.numberOfThumbsPerScreen:b.total_images));k.height((thumbsHolder_Thumb.height()+1)*(a.numberOfThumbsPerScreen<b.total_images?a.numberOfThumbsPerScreen:b.total_images));h.css({padding:a.playlistPadding+
 "px"});var J=a.showPlaylist&&a.showPlaylistOnInit?b.audioPlayerHeight+v.height()+a.playlistTopPos:b.audioPlayerHeight;O.css({width:d.width()+2*a.playerPadding+"px",height:J+"px"});b.total_images>a.numberOfThumbsPerScreen&&a.showPlaylist?(q.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(n,w){I(w.value,b,a,thumbsHolder_Thumb,q,B)}}),q.css({display:"inline",position:"absolute",height:v.height()-16-2*a.playlistPadding+"px",left:d.width()+2*a.playerPadding-q.width()-
 a.playlistPadding+"px",top:b.audioPlayerHeight+a.playlistTopPos+a.playlistPadding+"px"}),a.showPlaylistOnInit||q.css({opacity:0,display:"none"}),e(".thumbsHolder_ThumbOFF",d).css({width:d.width()+2*a.playerPadding-q.width()-3*a.playlistPadding+"px"})):e(".thumbsHolder_ThumbOFF",d).css({width:d.width()+2*a.playerPadding-2*a.playlistPadding+"px"});k.mousewheel(function(n,w,K,Q){n.preventDefault();n=q.slider("value");if(1<parseInt(n)&&-1==parseInt(w)||100>parseInt(n)&&1==parseInt(w))n+=w,q.slider("value",
 n),I(n,b,a,thumbsHolder_Thumb,q,B)});var y=e(".thumbsHolder_ThumbOFF",d);y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor});y.on("click",function(){if(!b.is_changeSrc){a.autoPlay=!0;var n=e(this).attr("rel");y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor});b.current_img_no=n;z(a,"cookie_current_img_no",b.current_img_no);
 H(b,a,y,thumbsHolder_Thumb,q,B,d,g,C,A,r,D,G,c)}});y.on("mouseover",function(){e(this).css({background:a.playlistRecordBgOnColor,"border-bottom-color":a.playlistRecordBottomBorderOnColor,color:a.playlistRecordTextOnColor})});y.on("mouseout",function(){var n=e(this),w=n.attr("rel");b.current_img_no!=w&&n.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor})});b.cookie_initialVolume=F(a,"cookie_initialVolume");b.cookie_initialVolume&&
 (a.initialVolume=b.cookie_initialVolume);u.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(n,w){document.getElementById(b.audioID).volume=w.value;z(a,"cookie_initialVolume",w.value)},stop:function(n,w){}});document.getElementById(b.audioID).volume=a.initialVolume;u.css({background:a.volumeOffColor});e(".ui-slider-range",u).css({background:a.volumeOnColor});g.on("click",function(){var n=document.getElementById(b.audioID).paused;N();0==n?(document.getElementById(b.audioID).pause(),
 g.removeClass("AudioPause"),z(a,"cookie_autoPlay",!1)):(document.getElementById(b.audioID).play(),g.addClass("AudioPause"),z(a,"cookie_autoPlay",!0))});f.on("click",function(){document.getElementById(b.audioID).currentTime=0;N();document.getElementById(b.audioID).play();g.addClass("AudioPause");g.addClass("AudioPause")});p.on("click",function(){if(!b.is_changeSrc||b.is_very_first)a.autoPlay=!0,y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,
 color:a.playlistRecordTextOffColor}),a.shuffle?M(a,b):b.current_img_no==b.total_images-1?b.current_img_no=0:b.current_img_no++,z(a,"cookie_current_img_no",b.current_img_no),H(b,a,y,thumbsHolder_Thumb,q,B,d,g,C,A,r,D,G,c)});l.on("click",function(){if(!b.is_changeSrc||b.is_very_first)a.autoPlay=!0,y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor}),a.shuffle?M(a,b):0>b.current_img_no-1?b.current_img_no=b.total_images-
 1:b.current_img_no--,z(a,"cookie_current_img_no",b.current_img_no),H(b,a,y,thumbsHolder_Thumb,q,B,d,g,C,A,r,D,G,c)});m.on("click",function(){0>v.css("margin-top").substring(0,v.css("margin-top").length-2)?(aux_opacity=1,aux_display="block",aux_margin_top="0px",J=b.audioPlayerHeight+v.height()+a.playlistTopPos,v.css({display:aux_display}),b.total_images>a.numberOfThumbsPerScreen&&q.css({opacity:1,display:"block"})):(aux_opacity=0,aux_display="none",aux_margin_top="-20px",b.total_images>a.numberOfThumbsPerScreen&&
 q.css({opacity:0,display:"none"}),J=b.audioPlayerHeight);v.animate({opacity:aux_opacity,"margin-top":aux_margin_top},500,"easeOutQuad",function(){v.css({display:aux_display})});O.animate({height:J},500,"easeOutQuad",function(){})});x.on("click",function(){document.getElementById(b.audioID).muted?(document.getElementById(b.audioID).muted=!1,x.removeClass("VolumeButtonMuted"),z(a,"cookie_muteVolume",0)):(document.getElementById(b.audioID).muted=!0,x.addClass("VolumeButtonMuted"),z(a,"cookie_muteVolume",
 1))});B.swipe({swipeStatus:function(n,w,K,Q,V,W){"up"!=K&&"down"!=K||0==Q||(currentScrollVal=q.slider("value"),currentScrollVal="up"==K?currentScrollVal-1.5:currentScrollVal+1.5,q.slider("value",currentScrollVal),e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(U){U.preventDefault()}),I(currentScrollVal,b,a,thumbsHolder_Thumb,q,B))},threshold:100,maxTimeThreshold:500,fingers:"all"});e.audio1_html5.playPause=function(n){n=e("#"+n).parent(".audio1_html5");e(".AudioPlay",
 n).click()};document.getElementById(b.audioID).addEventListener("ended",function(){a.loop?p.click():e(".AudioPlay").removeClass("AudioPause")});b.cookie_timePlayed=F(a,"cookie_timePlayed");b.cookie_current_img_no=F(a,"cookie_current_img_no");b.cookie_autoPlay=F(a,"cookie_autoPlay");void 0!=b.cookie_current_img_no?b.current_img_no=b.cookie_current_img_no:a.shuffle&&M(a,b);a.continuouslyPlayOnAllPages&&z(a,"cookie_current_img_no",b.current_img_no);void 0!=b.cookie_autoPlay&&(a.autoPlay="true"==b.cookie_autoPlay?
 !0:!1);if(-1!=t.indexOf("ipad")||-1!=t.indexOf("iphone")||-1!=t.indexOf("ipod")||-1!=t.indexOf("webos")||-1!=t.indexOf("android"))a.autoPlay=!1;H(b,a,y,thumbsHolder_Thumb,q,B,d,g,C,A,r,D,G,c);b.cookie_muteVolume=F(a,"cookie_muteVolume");1<=b.cookie_muteVolume&&x.click();b.timeupdateInterval=setInterval(function(){S(b,a,d,C,A,r,g,c,D,G)},300);document.getElementById(b.audioID).addEventListener("durationchange",function(){b.is_changeSrc&&(b.totalTime=document.getElementById(b.audioID).duration)});document.getElementById(b.audioID).addEventListener("canplay",
 function(){b.cookie_timePlayed&&(document.getElementById(b.audioID).currentTime=b.cookie_timePlayed,b.cookie_timePlayed=null);"iOS"===b.userOS&&b.totalTime!=document.getElementById(b.audioID).duration&&(a.isSliderInitialized&&(C.slider("destroy"),a.isSliderInitialized=!1),a.isProgressInitialized&&(A.progressbar("destroy"),a.isProgressInitialized=!1),b.totalTime=document.getElementById(b.audioID).duration,L(b,a,d,C,A,r,g,c),a.isProgressInitialized&&A.progressbar({value:b.audioPlayerWidth}));-1!=t.indexOf("opera")||
 ("iOS"===b.userOS||"Android"===b.userOS)&&b.is_very_first||(a.autoPlay?(N(),document.getElementById(b.audioID).play(),g.addClass("AudioPause")):0===document.getElementById(b.audioID).currentTime&&g.removeClass("AudioPause"))})})};e.fn.audio1_html5.defaults={skin:"whiteControllers",initialVolume:.5,autoPlay:!1,loop:!0,shuffle:!1,playerPadding:5,playerBg:"#000000",bufferEmptyColor:"#929292",bufferFullColor:"#454545",seekbarColor:"#ffffff",volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",
 songAuthorTitleColor:"#fffff",showRewindBut:!0,showPlayBut:!0,showPreviousBut:!0,showNextBut:!0,showPlaylistBut:!0,showVolumeBut:!0,showVolumeSliderBut:!0,showTimer:!0,showSeekBar:!0,showAuthor:!0,showTitle:!0,showPlaylist:!0,showPlaylistOnInit:!0,playlistTopPos:2,playlistBgColor:"#000000",playlistRecordBgOffColor:"#000000",playlistRecordBgOnColor:"#333333",playlistRecordBottomBorderOffColor:"#333333",playlistRecordBottomBorderOnColor:"#FFFFFF",playlistRecordTextOffColor:"#777777",playlistRecordTextOnColor:"#FFFFFF",
 numberOfThumbsPerScreen:7,playlistPadding:4,showPlaylistNumber:!0,centerPlugin:!1,continuouslyPlayOnAllPages:!1,isSliderInitialized:!1,isProgressInitialized:!1}})(jQuery);
